"""CLI tests for `downshift validate` and `downshift compare`."""

from __future__ import annotations

import json
from pathlib import Path

from typer.testing import CliRunner

from downshift.cli import app
from downshift.schema import CallSite, ModelRef, PromptMessage, ScanResult

runner = CliRunner()
BOB_NOTE = ["Bob: split from h.py::ask."]


def _site(
    site_id: str,
    *,
    model: str | None = "m-large",
    prompt: bool = True,
    via: str | None = None,
    enriched: bool = False,
    found_by: str = "ast",
    notes: list[str] | None = None,
) -> CallSite:
    file, function = site_id.split("::")
    return CallSite(
        id=site_id,
        file=file,
        line=1,
        function=function,
        api="openai.chat.completions",
        model=ModelRef(value=model, source="literal" if model else "env", expression="MODEL"),
        messages=[PromptMessage(role="user", content="{text}", resolved=prompt)],
        via=via,
        notes=notes or [],
        purpose="Does a thing." if enriched else None,
        output_contract="One word." if enriched else None,
        difficulty="easy" if enriched else None,
        grading="judge" if enriched else None,
        found_by=found_by,
    )


def _files(tmp_path: Path) -> tuple[Path, Path]:
    ast = ScanResult(
        root=".",
        files_scanned=2,
        call_sites=[_site("a.py::f"), _site("h.py::ask", model=None, prompt=False)],
    )
    audit = ScanResult(
        root=".",
        files_scanned=2,
        call_sites=[
            _site("a.py::f", enriched=True),
            _site("s.py::s", via="h.py::ask", enriched=True, found_by="bob", notes=BOB_NOTE),
            _site("u.py::u", via="h.py::ask", enriched=True, found_by="bob", notes=BOB_NOTE),
        ],
        generated_by="bob",
    )
    ast_path = tmp_path / "downshift.scan.json"
    audit_path = tmp_path / "downshift.audit.json"
    ast.write(ast_path)
    audit.write(audit_path)
    return ast_path, audit_path


# --- validate -----------------------------------------------------------------


def test_validate_valid_file(tmp_path: Path) -> None:
    _, audit = _files(tmp_path)
    result = runner.invoke(app, ["validate", str(audit)])
    assert result.exit_code == 0, result.output
    assert "Valid:" in result.output
    assert "3 call sites, generated by bob" in result.output
    assert "warning:" not in result.output


def test_validate_invalid_file_exits_1(tmp_path: Path) -> None:
    path = tmp_path / "bad.json"
    path.write_text('{"schema_version": 99, "call_sites": []}', encoding="utf-8")
    result = runner.invoke(app, ["validate", str(path)])
    assert result.exit_code == 1
    assert "Invalid:" in result.output
    assert "schema_version" in result.output


def test_validate_missing_file_exits_2(tmp_path: Path) -> None:
    result = runner.invoke(app, ["validate", str(tmp_path / "nope.json")])
    assert result.exit_code == 2
    assert "file not found" in result.output


def test_validate_warnings_pass_unless_strict(tmp_path: Path) -> None:
    unfinished = ScanResult(
        root=".",
        files_scanned=1,
        call_sites=[_site("a.py::f", found_by="bob", notes=BOB_NOTE)],
        generated_by="bob",
    )
    path = tmp_path / "downshift.audit.json"
    unfinished.write(path)

    relaxed = runner.invoke(app, ["validate", str(path)])
    assert relaxed.exit_code == 0, relaxed.output
    assert "warning: a.py::f: missing purpose" in relaxed.output

    strict = runner.invoke(app, ["validate", str(path), "--strict"])
    assert strict.exit_code == 1


# --- compare ------------------------------------------------------------------


def test_compare_prints_tables_and_summary(tmp_path: Path) -> None:
    ast, audit = _files(tmp_path)
    result = runner.invoke(app, ["compare", str(ast), str(audit)])
    assert result.exit_code == 0, result.output
    assert "Scan vs audit" in result.output
    assert "Models resolved" in result.output
    assert "split" in result.output
    assert (
        "ast: 2 call sites, 1 models resolved | bob: 3 call sites, 3 models resolved"
        in result.output
    )


def test_compare_json(tmp_path: Path) -> None:
    ast, audit = _files(tmp_path)
    result = runner.invoke(app, ["compare", str(ast), str(audit), "--json"])
    assert result.exit_code == 0, result.output
    data = json.loads(result.output)
    assert data["metrics"][0] == {"name": "Call sites", "ast": 2, "audit": 3}
    kinds = {c["id"]: c["kind"] for c in data["changes"]}
    assert kinds["h.py::ask"] == "split"
    assert kinds["s.py::s"] == "added"


def test_compare_same_producer_uses_before_after_labels(tmp_path: Path) -> None:
    ast, _ = _files(tmp_path)
    result = runner.invoke(app, ["compare", str(ast), str(ast)])
    assert result.exit_code == 0, result.output
    assert "before: 2 call sites" in result.output


def test_compare_bad_input_exits_2(tmp_path: Path) -> None:
    ast, _ = _files(tmp_path)
    result = runner.invoke(app, ["compare", str(ast), str(tmp_path / "nope.json")])
    assert result.exit_code == 2
    assert "not found" in result.output
