"""Downshift command line interface."""

import json
from pathlib import Path

import typer
from rich.console import Console
from rich.table import Table

from downshift import __version__
from downshift.audit import Comparison, compare_scans, validate_file
from downshift.config import ConfigError, resolve_config
from downshift.evals import EvalReport, check_eval_dir
from downshift.scanner import scan_path
from downshift.schema import ScanResult, SchemaError

DEFAULT_OUT = Path(".downshift") / "callsites.json"

app = typer.Typer(
    name="downshift",
    help=(
        "Find every LLM call in your repo, prove which ones can use cheaper "
        "models, and show the cost impact of every PR."
    ),
    no_args_is_help=True,
    add_completion=False,
)


def _version_callback(value: bool) -> None:
    if value:
        typer.echo(f"downshift {__version__}")
        raise typer.Exit()


@app.callback()
def main_callback(
    version: bool = typer.Option(
        False,
        "--version",
        callback=_version_callback,
        is_eager=True,
        help="Show the version and exit.",
    ),
) -> None:
    """Downshift: cut LLM costs per PR."""


def _not_implemented(name: str) -> None:
    typer.echo(f"`downshift {name}` is not implemented yet.", err=True)
    raise typer.Exit(code=1)


def _fail(message: str) -> None:
    typer.echo(f"Error: {message}", err=True)
    raise typer.Exit(code=2)


# --- scan ---------------------------------------------------------------------


@app.command()
def scan(
    path: Path = typer.Argument(Path("."), help="Repository directory or Python file to scan."),
    config: Path | None = typer.Option(
        None,
        "--config",
        "-c",
        help="Config file. Default: downshift.yaml in PATH, if present.",
    ),
    out: Path | None = typer.Option(
        None,
        "--out",
        "-o",
        help="Where to write callsites.json. Default: PATH/.downshift/callsites.json.",
    ),
    as_json: bool = typer.Option(
        False, "--json", help="Print the JSON to stdout instead of a table."
    ),
) -> None:
    """Find every LLM call site in a repository."""
    try:
        cfg = resolve_config(config, path)
        result = scan_path(path, cfg.scan)
    except (ConfigError, FileNotFoundError) as exc:
        _fail(str(exc))
        return

    if as_json:
        typer.echo(result.to_json(), nl=False)
        if out is not None:
            result.write(out)
        return

    target = out if out is not None else _default_out(path)
    result.write(target)
    _print_table(result)

    summary = result.summary()
    total = summary["call_sites"]
    typer.echo(
        f"{total} call sites in {summary['files_scanned']} files, "
        f"models resolved {summary['models_resolved']}/{total}, "
        f"prompts resolved {summary['prompts_resolved']}/{total}"
    )
    for warning in result.warnings:
        typer.echo(f"warning: {warning}", err=True)
    typer.echo(f"Wrote {target}")


def _default_out(path: Path) -> Path:
    base = path if path.is_dir() else path.parent
    return base / DEFAULT_OUT


def _print_table(result: ScanResult) -> None:
    table = Table(title=f"LLM call sites in {result.root}")
    table.add_column("File", no_wrap=True)
    table.add_column("Function", no_wrap=True)
    table.add_column("Line", justify="right")
    table.add_column("Model", no_wrap=True)
    table.add_column("Source")
    table.add_column("Prompt")
    table.add_column("Output")
    for site in result.call_sites:
        table.add_row(
            site.file,
            site.function,
            str(site.line),
            site.model.value or "[red]?[/red]",
            site.model.source,
            "known" if site.prompt_resolved else "[yellow]runtime[/yellow]",
            site.output_format,
        )
    Console().print(table)


# --- validate -----------------------------------------------------------------


@app.command()
def validate(
    path: Path = typer.Argument(..., help="callsites or audit JSON file to check."),
    strict: bool = typer.Option(False, "--strict", help="Treat warnings as errors."),
) -> None:
    """Check a callsites or audit file against the schema."""
    if not path.is_file():
        _fail(f"file not found: {path}")
        return

    report = validate_file(path)
    result = report.result
    if report.error is not None or result is None:
        typer.echo(f"Invalid: {report.error}", err=True)
        raise typer.Exit(code=1)

    summary = result.summary()
    total = summary["call_sites"]
    typer.echo(
        f"Valid: {path} ({total} call sites, generated by {result.generated_by}, "
        f"models resolved {summary['models_resolved']}/{total}, "
        f"prompts resolved {summary['prompts_resolved']}/{total})"
    )
    for warning in report.warnings:
        typer.echo(f"warning: {warning}", err=True)
    if strict and report.warnings:
        raise typer.Exit(code=1)


# --- compare ------------------------------------------------------------------


@app.command()
def compare(
    ast_file: Path = typer.Argument(..., help="Scan output from `downshift scan`."),
    audit_file: Path = typer.Argument(..., help="Audit output from the Bob auditor."),
    as_json: bool = typer.Option(False, "--json", help="Print the comparison as JSON."),
) -> None:
    """Compare the ast scan with a Bob audit, side by side."""
    try:
        before = ScanResult.load(ast_file)
        after = ScanResult.load(audit_file)
    except SchemaError as exc:
        _fail(str(exc))
        return

    comparison = compare_scans(before, after)
    if as_json:
        typer.echo(json.dumps(comparison.to_dict(), indent=2))
        return

    left, right = before.generated_by, after.generated_by
    if left == right:
        left, right = "before", "after"
    _print_comparison(comparison, left, right)

    b, a = before.summary(), after.summary()
    typer.echo(
        f"{left}: {b['call_sites']} call sites, {b['models_resolved']} models resolved | "
        f"{right}: {a['call_sites']} call sites, {a['models_resolved']} models resolved"
    )


def _print_comparison(comparison: Comparison, left: str, right: str) -> None:
    console = Console()
    metrics = Table(title="Scan vs audit")
    metrics.add_column("Metric")
    metrics.add_column(left, justify="right")
    metrics.add_column(right, justify="right")
    for metric in comparison.metrics:
        metrics.add_row(metric.name, str(metric.ast), str(metric.audit))
    console.print(metrics)

    changes = Table(title="Call site changes")
    changes.add_column("Call site", no_wrap=True)
    changes.add_column("Change")
    changes.add_column("Detail")
    for change in comparison.changes:
        changes.add_row(change.id, change.kind, change.detail)
    console.print(changes)


# --- check-evals --------------------------------------------------------------


@app.command("check-evals")
def check_evals(
    directory: Path = typer.Argument(..., help="Folder of <slug>.jsonl eval files."),
    callsites: Path = typer.Option(
        ..., "--callsites", help="Audit (or callsites) JSON the eval files belong to."
    ),
    strict: bool = typer.Option(False, "--strict", help="Treat warnings as errors."),
) -> None:
    """Check eval files against the call sites they test."""
    if not directory.is_dir():
        _fail(f"folder not found: {directory}")
        return
    try:
        result = ScanResult.load(callsites)
    except SchemaError as exc:
        _fail(str(exc))
        return

    reports = check_eval_dir(directory, result.call_sites)
    _print_eval_reports(reports)

    errors = sum(len(r.errors) for r in reports)
    warnings = sum(len(r.warnings) for r in reports)
    cases = sum(r.cases for r in reports)
    files = sum(1 for r in reports if r.path.exists())
    for r in reports:
        for message in r.errors:
            typer.echo(f"error: {r.path.name}: {message}", err=True)
        for message in r.warnings:
            typer.echo(f"warning: {r.path.name}: {message}", err=True)
    typer.echo(f"{files} eval files, {cases} cases, {errors} errors, {warnings} warnings")
    if errors or (strict and warnings):
        raise typer.Exit(code=1)


def _print_eval_reports(reports: list[EvalReport]) -> None:
    table = Table(title="Eval sets")
    table.add_column("Call site", overflow="fold")
    table.add_column("Grading")
    table.add_column("Cases", justify="right")
    table.add_column("Status")
    for r in reports:
        if r.errors:
            status = f"[red]{len(r.errors)} errors[/red]"
        elif r.warnings:
            status = f"[yellow]{len(r.warnings)} warnings[/yellow]"
        else:
            status = "[green]ok[/green]"
        table.add_row(r.site_id or "?", r.grading or "-", str(r.cases), status)
    Console().print(table)


# --- not implemented yet ------------------------------------------------------


@app.command()
def evalgen() -> None:
    """Generate an eval set for each call site."""
    _not_implemented("evalgen")


@app.command()
def run() -> None:
    """Run evals across candidate models."""
    _not_implemented("run")


@app.command()
def report() -> None:
    """Render the cost and quality report."""
    _not_implemented("report")


@app.command()
def diff() -> None:
    """Show the projected LLM cost change between two git refs."""
    _not_implemented("diff")


@app.command()
def dashboard() -> None:
    """Build the static HTML dashboard."""
    _not_implemented("dashboard")


def main() -> None:
    app()
